-- SQL script to populate sentences table with 800 complex French sentences
-- Auto-generated by generate_sentences.py

CREATE TABLE IF NOT EXISTS sentences (
    id SERIAL PRIMARY KEY,
    text TEXT NOT NULL,
    verbs JSONB NOT NULL,
    tenses TEXT[] NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

TRUNCATE TABLE sentences RESTART IDENTITY CASCADE;

INSERT INTO sentences (text, verbs, tenses) VALUES
('Le guépard (courir) à une vitesse impressionnante dans la savane africaine.', '[{"infinitive": "courir", "position": 0, "subject": "Le guépard"}]', '{"present","imparfait","passe_compose"}'),
('Cet animal (posséder) un pelage très reconnaissable, jaune tacheté de noir.', '[{"infinitive": "posséder", "position": 0, "subject": "Cet animal"}]', '{"present","imparfait"}'),
('Les oiseaux migrateurs (partir) vers le sud dès que l''automne (arriver).', '[{"infinitive": "partir", "position": 0, "subject": "Les oiseaux migrateurs"}, {"infinitive": "arriver", "position": 1, "subject": "l''automne"}]', '{"present","imparfait","futur_simple"}'),
('Ces petits poissons colorés (nager) gracieusement dans l''aquarium.', '[{"infinitive": "nager", "position": 0, "subject": "Ces petits poissons colorés"}]', '{"present","imparfait"}'),
('Le lion (rugir) puissamment pour marquer son territoire.', '[{"infinitive": "rugir", "position": 0, "subject": "Le lion"}]', '{"present","imparfait","passe_compose"}'),
('Les dauphins (sauter) hors de l''eau en formant des arcs gracieux.', '[{"infinitive": "sauter", "position": 0, "subject": "Les dauphins"}]', '{"present","imparfait","passe_compose"}'),
('L''aigle royal (planer) majestueusement au-dessus des montagnes.', '[{"infinitive": "planer", "position": 0, "subject": "L''aigle royal"}]', '{"present","imparfait"}'),
('Les abeilles (butiner) les fleurs du jardin pendant toute la matinée.', '[{"infinitive": "butiner", "position": 0, "subject": "Les abeilles"}]', '{"present","imparfait","passe_compose"}'),
('Le chat domestique (dormir) plus de quinze heures par jour.', '[{"infinitive": "dormir", "position": 0, "subject": "Le chat domestique"}]', '{"present","imparfait"}'),
('Ces magnifiques roses rouges (pousser) dans le jardin de ma grand-mère chaque printemps.', '[{"infinitive": "pousser", "position": 0, "subject": "Ces magnifiques roses rouges"}]', '{"present","imparfait","futur_simple"}'),
('Marie et Sophie (aller) au marché tous les samedis matin.', '[{"infinitive": "aller", "position": 0, "subject": "Marie et Sophie"}]', '{"present","imparfait","futur_simple"}'),
('Quand j''(avoir) 1 an, mon père (proposer) que nous partions en voyage en famille.', '[{"infinitive": "avoir", "position": 0, "subject": "j''"}, {"infinitive": "proposer", "position": 1, "subject": "mon père"}]', '{"imparfait","passe_compose"}');

SELECT COUNT(*) as total_sentences FROM sentences;
