version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: verber-postgres-prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-verber_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-verber_password}
      POSTGRES_DB: ${POSTGRES_DB:-verber_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Remove external port mapping - only accessible internally
    expose:
      - "5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-verber_user} -d ${POSTGRES_DB:-verber_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - verber-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: verber-redis-prod
    restart: always
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    # Remove external port mapping - only accessible internally
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - verber-network

  # Go Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: verber-backend-prod
    restart: always
    # Expose port for host nginx to access
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER:-verber_user}:${POSTGRES_PASSWORD:-verber_password}@postgres:5432/${POSTGRES_DB:-verber_db}?sslmode=disable
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL:-https://verber.sicole.com}
      - ENVIRONMENT=production
      - PORT=8080
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:8080/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - verber-network

  # React Frontend (Production) - Served through nginx proxy
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-https://verber.sicole.com/api}
        - REACT_APP_WS_URL=${REACT_APP_WS_URL:-wss://verber.sicole.com}
    container_name: verber-frontend-prod
    restart: always
    # Map to port 3001 for nginx proxy
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - verber-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  verber-network:
    driver: bridge