-- Auto-generated SQL to add missing verbs
-- Generated from convert_verbs_to_sql.py

-- Adding conduire
INSERT INTO verbs (infinitive, past_participle, present_participle, auxiliary, pronomininal_form)
VALUES ('conduire', 'Conduit', 'Conduisant', 'avoir', 'se conduire');

INSERT INTO verb_conjugations (verb_id, present_1, present_2, present_3, present_4, present_5, present_6, imparfait_1, imparfait_2, imparfait_3, imparfait_4, imparfait_5, imparfait_6, passe_simple_1, passe_simple_2, passe_simple_3, passe_simple_4, passe_simple_5, passe_simple_6, futur_simple_1, futur_simple_2, futur_simple_3, futur_simple_4, futur_simple_5, futur_simple_6, passe_compose_1, passe_compose_2, passe_compose_3, passe_compose_4, passe_compose_5, passe_compose_6, plus_que_parfait_1, plus_que_parfait_2, plus_que_parfait_3, plus_que_parfait_4, plus_que_parfait_5, plus_que_parfait_6, passe_anterieur_1, passe_anterieur_2, passe_anterieur_3, passe_anterieur_4, passe_anterieur_5, passe_anterieur_6, futur_anterieur_1, futur_anterieur_2, futur_anterieur_3, futur_anterieur_4, futur_anterieur_5, futur_anterieur_6, subjonctif_present_1, subjonctif_present_2, subjonctif_present_3, subjonctif_present_4, subjonctif_present_5, subjonctif_present_6, subjonctif_imparfait_1, subjonctif_imparfait_2, subjonctif_imparfait_3, subjonctif_imparfait_4, subjonctif_imparfait_5, subjonctif_imparfait_6, subjonctif_passe_1, subjonctif_passe_2, subjonctif_passe_3, subjonctif_passe_4, subjonctif_passe_5, subjonctif_passe_6, subjonctif_plus_que_parfait_1, subjonctif_plus_que_parfait_2, subjonctif_plus_que_parfait_3, subjonctif_plus_que_parfait_4, subjonctif_plus_que_parfait_5, subjonctif_plus_que_parfait_6, conditionnel_present_1, conditionnel_present_2, conditionnel_present_3, conditionnel_present_4, conditionnel_present_5, conditionnel_present_6, conditionnel_passe_1, conditionnel_passe_2, conditionnel_passe_3, conditionnel_passe_4, conditionnel_passe_5, conditionnel_passe_6, conditionnel_passe_ii_1, conditionnel_passe_ii_2, conditionnel_passe_ii_3, conditionnel_passe_ii_4, conditionnel_passe_ii_5, conditionnel_passe_ii_6, imperatif_1, imperatif_2, imperatif_3, imperatif_4, imperatif_5, imperatif_6, imperatif_passe_1, imperatif_passe_2, imperatif_passe_3, imperatif_passe_4, imperatif_passe_5, imperatif_passe_6)
SELECT id, 'Conduis', 'Conduis', 'Conduit', 'Conduisons', 'Conduisez', 'Conduisent', 'Conduisais', 'Conduisais', 'Conduisait', 'Conduisions', 'Conduisiez', 'Conduisaient', 'Conduisis', 'Conduisis', 'Conduisit', 'Conduisîmes', 'Conduisîtes', 'Conduisirent', 'Conduirai', 'Conduiras', 'Conduira', 'Conduirons', 'Conduirez', 'Conduiront', 'ai conduit', 'as conduit', 'a conduit', 'avons conduit', 'avez conduit', 'ont conduit', 'avais conduit', 'avais conduit', 'avait conduit', 'avions conduit', 'aviez conduit', 'avaient conduit', 'eus conduit', 'eus conduit', 'eut conduit', 'eûmes conduit', 'eûtes conduit', 'eurent conduit', 'aurai conduit', 'auras conduit', 'aura conduit', 'aurons conduit', 'aurez conduit', 'auront conduit', 'Conduise', 'Conduises', 'Conduise', 'Conduisions', 'Conduisiez', 'Conduisent', 'Conduisisse', 'Conduisisses', 'Conduisît', 'Conduisissions', 'Conduisissiez', 'Conduisissent', 'aie conduit', 'aies conduit', 'ait conduit', 'ayons conduit', 'ayez conduit', 'aient conduit', 'eusse conduit', 'eusses conduit', 'eût conduit', 'eussions conduit', 'eussiez conduit', 'eussent conduit', 'Conduirais', 'Conduirais', 'Conduirait', 'Conduirions', 'Conduiriez', 'Conduiraient', 'aurais conduit', 'aurais conduit', 'aurait conduit', 'aurions conduit', 'auriez conduit', 'auraient conduit', 'eusse conduit', 'eusses conduit', 'eût conduit', 'eussions conduit', 'eussiez conduit', 'eussent conduit', '', 'Conduis !', '', 'Conduisons !', 'Conduisez !', '', '', 'aie conduit !', '', 'ayons conduit !', 'ayez conduit !', ''
FROM verbs WHERE infinitive = 'conduire';


-- Adding connaître
INSERT INTO verbs (infinitive, past_participle, present_participle, auxiliary, pronomininal_form)
VALUES ('connaître', 'Connu', 'Connaissant', 'avoir', 'se connaître');

INSERT INTO verb_conjugations (verb_id, present_1, present_2, present_3, present_4, present_5, present_6, imparfait_1, imparfait_2, imparfait_3, imparfait_4, imparfait_5, imparfait_6, passe_simple_1, passe_simple_2, passe_simple_3, passe_simple_4, passe_simple_5, passe_simple_6, futur_simple_1, futur_simple_2, futur_simple_3, futur_simple_4, futur_simple_5, futur_simple_6, passe_compose_1, passe_compose_2, passe_compose_3, passe_compose_4, passe_compose_5, passe_compose_6, plus_que_parfait_1, plus_que_parfait_2, plus_que_parfait_3, plus_que_parfait_4, plus_que_parfait_5, plus_que_parfait_6, passe_anterieur_1, passe_anterieur_2, passe_anterieur_3, passe_anterieur_4, passe_anterieur_5, passe_anterieur_6, futur_anterieur_1, futur_anterieur_2, futur_anterieur_3, futur_anterieur_4, futur_anterieur_5, futur_anterieur_6, subjonctif_present_1, subjonctif_present_2, subjonctif_present_3, subjonctif_present_4, subjonctif_present_5, subjonctif_present_6, subjonctif_imparfait_1, subjonctif_imparfait_2, subjonctif_imparfait_3, subjonctif_imparfait_4, subjonctif_imparfait_5, subjonctif_imparfait_6, subjonctif_passe_1, subjonctif_passe_2, subjonctif_passe_3, subjonctif_passe_4, subjonctif_passe_5, subjonctif_passe_6, subjonctif_plus_que_parfait_1, subjonctif_plus_que_parfait_2, subjonctif_plus_que_parfait_3, subjonctif_plus_que_parfait_4, subjonctif_plus_que_parfait_5, subjonctif_plus_que_parfait_6, conditionnel_present_1, conditionnel_present_2, conditionnel_present_3, conditionnel_present_4, conditionnel_present_5, conditionnel_present_6, conditionnel_passe_1, conditionnel_passe_2, conditionnel_passe_3, conditionnel_passe_4, conditionnel_passe_5, conditionnel_passe_6, conditionnel_passe_ii_1, conditionnel_passe_ii_2, conditionnel_passe_ii_3, conditionnel_passe_ii_4, conditionnel_passe_ii_5, conditionnel_passe_ii_6, imperatif_1, imperatif_2, imperatif_3, imperatif_4, imperatif_5, imperatif_6, imperatif_passe_1, imperatif_passe_2, imperatif_passe_3, imperatif_passe_4, imperatif_passe_5, imperatif_passe_6)
SELECT id, 'Connais', 'Connais', 'Connaît', 'Connaissons', 'Connaissez', 'Connaissent', 'Connaissais', 'Connaissais', 'Connaissait', 'Connaissions', 'Connaissiez', 'Connaissaient', 'Connus', 'Connus', 'Connut', 'Connûmes', 'Connûtes', 'Connurent', 'Connaîtrai', 'Connaîtras', 'Connaîtra', 'Connaîtrons', 'Connaîtrez', 'Connaîtront', 'ai connu', 'as connu', 'a connu', 'avons connu', 'avez connu', 'ont connu', 'avais connu', 'avais connu', 'avait connu', 'avions connu', 'aviez connu', 'avaient connu', 'eus connu', 'eus connu', 'eut connu', 'eûmes connu', 'eûtes connu', 'eurent connu', 'aurai connu', 'auras connu', 'aura connu', 'aurons connu', 'aurez connu', 'auront connu', 'Connaisse', 'Connaisses', 'Connaisse', 'Connaissions', 'Connaissiez', 'Connaissent', 'Connusse', 'Connusses', 'Connût', 'Connussions', 'Connussiez', 'Connussent', 'aie connu', 'aies connu', 'ait connu', 'ayons connu', 'ayez connu', 'aient connu', 'eusse connu', 'eusses connu', 'eût connu', 'eussions connu', 'eussiez connu', 'eussent connu', 'Connaîtrais', 'Connaîtrais', 'Connaîtrait', 'Connaîtrions', 'Connaîtriez', 'Connaîtraient', 'aurais connu', 'aurais connu', 'aurait connu', 'aurions connu', 'auriez connu', 'auraient connu', 'eusse connu', 'eusses connu', 'eût connu', 'eussions connu', 'eussiez connu', 'eussent connu', '', 'Connais !', '', 'Connaissons !', 'Connaissez !', '', '', 'aie connu !', '', 'ayons connu !', 'ayez connu !', ''
FROM verbs WHERE infinitive = 'connaître';


-- Adding construire
INSERT INTO verbs (infinitive, past_participle, present_participle, auxiliary, pronomininal_form)
VALUES ('construire', 'Construit', 'Construisant', 'avoir', 'se construire');

INSERT INTO verb_conjugations (verb_id, present_1, present_2, present_3, present_4, present_5, present_6, imparfait_1, imparfait_2, imparfait_3, imparfait_4, imparfait_5, imparfait_6, passe_simple_1, passe_simple_2, passe_simple_3, passe_simple_4, passe_simple_5, passe_simple_6, futur_simple_1, futur_simple_2, futur_simple_3, futur_simple_4, futur_simple_5, futur_simple_6, passe_compose_1, passe_compose_2, passe_compose_3, passe_compose_4, passe_compose_5, passe_compose_6, plus_que_parfait_1, plus_que_parfait_2, plus_que_parfait_3, plus_que_parfait_4, plus_que_parfait_5, plus_que_parfait_6, passe_anterieur_1, passe_anterieur_2, passe_anterieur_3, passe_anterieur_4, passe_anterieur_5, passe_anterieur_6, futur_anterieur_1, futur_anterieur_2, futur_anterieur_3, futur_anterieur_4, futur_anterieur_5, futur_anterieur_6, subjonctif_present_1, subjonctif_present_2, subjonctif_present_3, subjonctif_present_4, subjonctif_present_5, subjonctif_present_6, subjonctif_imparfait_1, subjonctif_imparfait_2, subjonctif_imparfait_3, subjonctif_imparfait_4, subjonctif_imparfait_5, subjonctif_imparfait_6, subjonctif_passe_1, subjonctif_passe_2, subjonctif_passe_3, subjonctif_passe_4, subjonctif_passe_5, subjonctif_passe_6, subjonctif_plus_que_parfait_1, subjonctif_plus_que_parfait_2, subjonctif_plus_que_parfait_3, subjonctif_plus_que_parfait_4, subjonctif_plus_que_parfait_5, subjonctif_plus_que_parfait_6, conditionnel_present_1, conditionnel_present_2, conditionnel_present_3, conditionnel_present_4, conditionnel_present_5, conditionnel_present_6, conditionnel_passe_1, conditionnel_passe_2, conditionnel_passe_3, conditionnel_passe_4, conditionnel_passe_5, conditionnel_passe_6, conditionnel_passe_ii_1, conditionnel_passe_ii_2, conditionnel_passe_ii_3, conditionnel_passe_ii_4, conditionnel_passe_ii_5, conditionnel_passe_ii_6, imperatif_1, imperatif_2, imperatif_3, imperatif_4, imperatif_5, imperatif_6, imperatif_passe_1, imperatif_passe_2, imperatif_passe_3, imperatif_passe_4, imperatif_passe_5, imperatif_passe_6)
SELECT id, 'Construis', 'Construis', 'Construit', 'Construisons', 'Construisez', 'Construisent', 'Construisais', 'Construisais', 'Construisait', 'Construisions', 'Construisiez', 'Construisaient', 'Construisis', 'Construisis', 'Construisit', 'Construisîmes', 'Construisîtes', 'Construisirent', 'Construirai', 'Construiras', 'Construira', 'Construirons', 'Construirez', 'Construiront', 'ai construit', 'as construit', 'a construit', 'avons construit', 'avez construit', 'ont construit', 'avais construit', 'avais construit', 'avait construit', 'avions construit', 'aviez construit', 'avaient construit', 'eus construit', 'eus construit', 'eut construit', 'eûmes construit', 'eûtes construit', 'eurent construit', 'aurai construit', 'auras construit', 'aura construit', 'aurons construit', 'aurez construit', 'auront construit', 'Construise', 'Construises', 'Construise', 'Construisions', 'Construisiez', 'Construisent', 'Construisisse', 'Construisisses', 'Construisît', 'Construisissions', 'Construisissiez', 'Construisissent', 'aie construit', 'aies construit', 'ait construit', 'ayons construit', 'ayez construit', 'aient construit', 'eusse construit', 'eusses construit', 'eût construit', 'eussions construit', 'eussiez construit', 'eussent construit', 'Construirais', 'Construirais', 'Construirait', 'Construirions', 'Construiriez', 'Construiraient', 'aurais construit', 'aurais construit', 'aurait construit', 'aurions construit', 'auriez construit', 'auraient construit', 'eusse construit', 'eusses construit', 'eût construit', 'eussions construit', 'eussiez construit', 'eussent construit', '', 'Construis !', '', 'Construisons !', 'Construisez !', '', '', 'aie construit !', '', 'ayons construit !', 'ayez construit !', ''
FROM verbs WHERE infinitive = 'construire';


-- Adding consulter
INSERT INTO verbs (infinitive, past_participle, present_participle, auxiliary, pronomininal_form)
VALUES ('consulter', 'Consulté', 'Consultant', 'avoir', '');

INSERT INTO verb_conjugations (verb_id, present_1, present_2, present_3, present_4, present_5, present_6, imparfait_1, imparfait_2, imparfait_3, imparfait_4, imparfait_5, imparfait_6, passe_simple_1, passe_simple_2, passe_simple_3, passe_simple_4, passe_simple_5, passe_simple_6, futur_simple_1, futur_simple_2, futur_simple_3, futur_simple_4, futur_simple_5, futur_simple_6, passe_compose_1, passe_compose_2, passe_compose_3, passe_compose_4, passe_compose_5, passe_compose_6, plus_que_parfait_1, plus_que_parfait_2, plus_que_parfait_3, plus_que_parfait_4, plus_que_parfait_5, plus_que_parfait_6, passe_anterieur_1, passe_anterieur_2, passe_anterieur_3, passe_anterieur_4, passe_anterieur_5, passe_anterieur_6, futur_anterieur_1, futur_anterieur_2, futur_anterieur_3, futur_anterieur_4, futur_anterieur_5, futur_anterieur_6, subjonctif_present_1, subjonctif_present_2, subjonctif_present_3, subjonctif_present_4, subjonctif_present_5, subjonctif_present_6, subjonctif_imparfait_1, subjonctif_imparfait_2, subjonctif_imparfait_3, subjonctif_imparfait_4, subjonctif_imparfait_5, subjonctif_imparfait_6, subjonctif_passe_1, subjonctif_passe_2, subjonctif_passe_3, subjonctif_passe_4, subjonctif_passe_5, subjonctif_passe_6, subjonctif_plus_que_parfait_1, subjonctif_plus_que_parfait_2, subjonctif_plus_que_parfait_3, subjonctif_plus_que_parfait_4, subjonctif_plus_que_parfait_5, subjonctif_plus_que_parfait_6, conditionnel_present_1, conditionnel_present_2, conditionnel_present_3, conditionnel_present_4, conditionnel_present_5, conditionnel_present_6, conditionnel_passe_1, conditionnel_passe_2, conditionnel_passe_3, conditionnel_passe_4, conditionnel_passe_5, conditionnel_passe_6, conditionnel_passe_ii_1, conditionnel_passe_ii_2, conditionnel_passe_ii_3, conditionnel_passe_ii_4, conditionnel_passe_ii_5, conditionnel_passe_ii_6, imperatif_1, imperatif_2, imperatif_3, imperatif_4, imperatif_5, imperatif_6, imperatif_passe_1, imperatif_passe_2, imperatif_passe_3, imperatif_passe_4, imperatif_passe_5, imperatif_passe_6)
SELECT id, 'Consulte', 'Consultes', 'Consulte', 'Consultons', 'Consultez', 'Consultent', 'Consultais', 'Consultais', 'Consultait', 'Consultions', 'Consultiez', 'Consultaient', 'Consultai', 'Consultas', 'Consulta', 'Consultâmes', 'Consultâtes', 'Consultèrent', 'Consulterai', 'Consulteras', 'Consultera', 'Consulterons', 'Consulterez', 'Consulteront', 'ai consulté', 'as consulté', 'a consulté', 'avons consulté', 'avez consulté', 'ont consulté', 'avais consulté', 'avais consulté', 'avait consulté', 'avions consulté', 'aviez consulté', 'avaient consulté', 'eus consulté', 'eus consulté', 'eut consulté', 'eûmes consulté', 'eûtes consulté', 'eurent consulté', 'aurai consulté', 'auras consulté', 'aura consulté', 'aurons consulté', 'aurez consulté', 'auront consulté', 'Consulte', 'Consultes', 'Consulte', 'Consultions', 'Consultiez', 'Consultent', 'Consultasse', 'Consultasses', 'Consultât', 'Consultassions', 'Consultassiez', 'Consultassent', 'aie consulté', 'aies consulté', 'ait consulté', 'ayons consulté', 'ayez consulté', 'aient consulté', 'eusse consulté', 'eusses consulté', 'eût consulté', 'eussions consulté', 'eussiez consulté', 'eussent consulté', 'Consulterais', 'Consulterais', 'Consulterait', 'Consulterions', 'Consulteriez', 'Consulteraient', 'aurais consulté', 'aurais consulté', 'aurait consulté', 'aurions consulté', 'auriez consulté', 'auraient consulté', 'eusse consulté', 'eusses consulté', 'eût consulté', 'eussions consulté', 'eussiez consulté', 'eussent consulté', '', 'Consulte !', '', 'Consultons !', 'Consultez !', '', '', 'aie consulté !', '', 'ayons consulté !', 'ayez consulté !', ''
FROM verbs WHERE infinitive = 'consulter';


-- Adding contenir
INSERT INTO verbs (infinitive, past_participle, present_participle, auxiliary, pronomininal_form)
VALUES ('contenir', 'Contenu', 'Contenant', 'avoir', 'se contenir');

INSERT INTO verb_conjugations (verb_id, present_1, present_2, present_3, present_4, present_5, present_6, imparfait_1, imparfait_2, imparfait_3, imparfait_4, imparfait_5, imparfait_6, passe_simple_1, passe_simple_2, passe_simple_3, passe_simple_4, passe_simple_5, passe_simple_6, futur_simple_1, futur_simple_2, futur_simple_3, futur_simple_4, futur_simple_5, futur_simple_6, passe_compose_1, passe_compose_2, passe_compose_3, passe_compose_4, passe_compose_5, passe_compose_6, plus_que_parfait_1, plus_que_parfait_2, plus_que_parfait_3, plus_que_parfait_4, plus_que_parfait_5, plus_que_parfait_6, passe_anterieur_1, passe_anterieur_2, passe_anterieur_3, passe_anterieur_4, passe_anterieur_5, passe_anterieur_6, futur_anterieur_1, futur_anterieur_2, futur_anterieur_3, futur_anterieur_4, futur_anterieur_5, futur_anterieur_6, subjonctif_present_1, subjonctif_present_2, subjonctif_present_3, subjonctif_present_4, subjonctif_present_5, subjonctif_present_6, subjonctif_imparfait_1, subjonctif_imparfait_2, subjonctif_imparfait_3, subjonctif_imparfait_4, subjonctif_imparfait_5, subjonctif_imparfait_6, subjonctif_passe_1, subjonctif_passe_2, subjonctif_passe_3, subjonctif_passe_4, subjonctif_passe_5, subjonctif_passe_6, subjonctif_plus_que_parfait_1, subjonctif_plus_que_parfait_2, subjonctif_plus_que_parfait_3, subjonctif_plus_que_parfait_4, subjonctif_plus_que_parfait_5, subjonctif_plus_que_parfait_6, conditionnel_present_1, conditionnel_present_2, conditionnel_present_3, conditionnel_present_4, conditionnel_present_5, conditionnel_present_6, conditionnel_passe_1, conditionnel_passe_2, conditionnel_passe_3, conditionnel_passe_4, conditionnel_passe_5, conditionnel_passe_6, conditionnel_passe_ii_1, conditionnel_passe_ii_2, conditionnel_passe_ii_3, conditionnel_passe_ii_4, conditionnel_passe_ii_5, conditionnel_passe_ii_6, imperatif_1, imperatif_2, imperatif_3, imperatif_4, imperatif_5, imperatif_6, imperatif_passe_1, imperatif_passe_2, imperatif_passe_3, imperatif_passe_4, imperatif_passe_5, imperatif_passe_6)
SELECT id, 'Contiens', 'Contiens', 'Contient', 'Contenons', 'Contenez', 'Contiennent', 'Contenais', 'Contenais', 'Contenait', 'Contenions', 'Conteniez', 'Contenaient', 'Contins', 'Contins', 'Contint', 'Contînmes', 'Contîntes', 'Continrent', 'Contiendrai', 'Contiendras', 'Contiendra', 'Contiendrons', 'Contiendrez', 'Contiendront', 'ai contenu', 'as contenu', 'a contenu', 'avons contenu', 'avez contenu', 'ont contenu', 'avais contenu', 'avais contenu', 'avait contenu', 'avions contenu', 'aviez contenu', 'avaient contenu', 'eus contenu', 'eus contenu', 'eut contenu', 'eûmes contenu', 'eûtes contenu', 'eurent contenu', 'aurai contenu', 'auras contenu', 'aura contenu', 'aurons contenu', 'aurez contenu', 'auront contenu', 'Contienne', 'Contiennes', 'Contienne', 'Contenions', 'Conteniez', 'Contiennent', 'Continsse', 'Continsses', 'Contînt', 'Continssions', 'Continssiez', 'Continssent', 'aie contenu', 'aies contenu', 'ait contenu', 'ayons contenu', 'ayez contenu', 'aient contenu', 'eusse contenu', 'eusses contenu', 'eût contenu', 'eussions contenu', 'eussiez contenu', 'eussent contenu', 'Contiendrais', 'Contiendrais', 'Contiendrait', 'Contiendrions', 'Contiendriez', 'Contiendraient', 'aurais contenu', 'aurais contenu', 'aurait contenu', 'aurions contenu', 'auriez contenu', 'auraient contenu', 'eusse contenu', 'eusses contenu', 'eût contenu', 'eussions contenu', 'eussiez contenu', 'eussent contenu', '', 'Contiens !', '', 'Contenons !', 'Contenez !', '', '', 'aie contenu !', '', 'ayons contenu !', 'ayez contenu !', ''
FROM verbs WHERE infinitive = 'contenir';


-- Adding continuer
INSERT INTO verbs (infinitive, past_participle, present_participle, auxiliary, pronomininal_form)
VALUES ('continuer', 'Continué', 'Continuant', 'avoir', '');

INSERT INTO verb_conjugations (verb_id, present_1, present_2, present_3, present_4, present_5, present_6, imparfait_1, imparfait_2, imparfait_3, imparfait_4, imparfait_5, imparfait_6, passe_simple_1, passe_simple_2, passe_simple_3, passe_simple_4, passe_simple_5, passe_simple_6, futur_simple_1, futur_simple_2, futur_simple_3, futur_simple_4, futur_simple_5, futur_simple_6, passe_compose_1, passe_compose_2, passe_compose_3, passe_compose_4, passe_compose_5, passe_compose_6, plus_que_parfait_1, plus_que_parfait_2, plus_que_parfait_3, plus_que_parfait_4, plus_que_parfait_5, plus_que_parfait_6, passe_anterieur_1, passe_anterieur_2, passe_anterieur_3, passe_anterieur_4, passe_anterieur_5, passe_anterieur_6, futur_anterieur_1, futur_anterieur_2, futur_anterieur_3, futur_anterieur_4, futur_anterieur_5, futur_anterieur_6, subjonctif_present_1, subjonctif_present_2, subjonctif_present_3, subjonctif_present_4, subjonctif_present_5, subjonctif_present_6, subjonctif_imparfait_1, subjonctif_imparfait_2, subjonctif_imparfait_3, subjonctif_imparfait_4, subjonctif_imparfait_5, subjonctif_imparfait_6, subjonctif_passe_1, subjonctif_passe_2, subjonctif_passe_3, subjonctif_passe_4, subjonctif_passe_5, subjonctif_passe_6, subjonctif_plus_que_parfait_1, subjonctif_plus_que_parfait_2, subjonctif_plus_que_parfait_3, subjonctif_plus_que_parfait_4, subjonctif_plus_que_parfait_5, subjonctif_plus_que_parfait_6, conditionnel_present_1, conditionnel_present_2, conditionnel_present_3, conditionnel_present_4, conditionnel_present_5, conditionnel_present_6, conditionnel_passe_1, conditionnel_passe_2, conditionnel_passe_3, conditionnel_passe_4, conditionnel_passe_5, conditionnel_passe_6, conditionnel_passe_ii_1, conditionnel_passe_ii_2, conditionnel_passe_ii_3, conditionnel_passe_ii_4, conditionnel_passe_ii_5, conditionnel_passe_ii_6, imperatif_1, imperatif_2, imperatif_3, imperatif_4, imperatif_5, imperatif_6, imperatif_passe_1, imperatif_passe_2, imperatif_passe_3, imperatif_passe_4, imperatif_passe_5, imperatif_passe_6)
SELECT id, 'Continue', 'Continues', 'Continue', 'Continuons', 'Continuez', 'Continuent', 'Continuais', 'Continuais', 'Continuait', 'Continuions', 'Continuiez', 'Continuaient', 'Continuai', 'Continuas', 'Continua', 'Continuâmes', 'Continuâtes', 'Continuèrent', 'Continuerai', 'Continueras', 'Continuera', 'Continuerons', 'Continuerez', 'Continueront', 'ai continué', 'as continué', 'a continué', 'avons continué', 'avez continué', 'ont continué', 'avais continué', 'avais continué', 'avait continué', 'avions continué', 'aviez continué', 'avaient continué', 'eus continué', 'eus continué', 'eut continué', 'eûmes continué', 'eûtes continué', 'eurent continué', 'aurai continué', 'auras continué', 'aura continué', 'aurons continué', 'aurez continué', 'auront continué', 'Continue', 'Continues', 'Continue', 'Continuions', 'Continuiez', 'Continuent', 'Continuasse', 'Continuasses', 'Continuât', 'Continuassions', 'Continuassiez', 'Continuassent', 'aie continué', 'aies continué', 'ait continué', 'ayons continué', 'ayez continué', 'aient continué', 'eusse continué', 'eusses continué', 'eût continué', 'eussions continué', 'eussiez continué', 'eussent continué', 'Continuerais', 'Continuerais', 'Continuerait', 'Continuerions', 'Continueriez', 'Continueraient', 'aurais continué', 'aurais continué', 'aurait continué', 'aurions continué', 'auriez continué', 'auraient continué', 'eusse continué', 'eusses continué', 'eût continué', 'eussions continué', 'eussiez continué', 'eussent continué', '', 'Continue !', '', 'Continuons !', 'Continuez !', '', '', 'aie continué !', '', 'ayons continué !', 'ayez continué !', ''
FROM verbs WHERE infinitive = 'continuer';


