name: 🏥 Health Check

on:
  schedule:
    - cron: '*/15 * * * *'  # Every 15 minutes
  workflow_dispatch:  # Allow manual trigger

jobs:
  health-check:
    name: Check Application Health
    runs-on: ubuntu-latest
    
    steps:
    - name: 🏥 Check Frontend Health
      run: |
        if curl -f -s ${{ secrets.APP_URL || 'https://verber.sicole.com' }} >/dev/null; then
          echo "✅ Frontend is healthy"
        else
          echo "❌ Frontend health check failed"
          exit 1
        fi
    
    - name: 🏥 Check Backend API Health
      run: |
        api_url="${{ secrets.APP_URL || 'https://verber.sicole.com' }}/api/health"
        if curl -f -s "$api_url" >/dev/null; then
          echo "✅ Backend API is healthy"
        else
          echo "❌ Backend API health check failed"
          exit 1
        fi
    
    - name: 📊 Check Response Time
      run: |
        api_url="${{ secrets.APP_URL || 'https://verber.sicole.com' }}/api/health"
        response_time=$(curl -o /dev/null -s -w '%{time_total}\n' "$api_url")
        echo "Response time: ${response_time}s"
        
        # Alert if response time > 5 seconds
        if (( $(echo "$response_time > 5" | bc -l) )); then
          echo "⚠️ High response time detected: ${response_time}s"
        fi
    
    - name: 📢 Notify on Failure
      if: failure() && secrets.DISCORD_WEBHOOK != ''
      uses: sarisia/actions-status-discord@v1
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK }}
        title: "🚨 Verber Health Check Failed"
        description: |
          The application health check has failed.
          Please investigate the server status immediately.
          
          **Time:** ${{ github.event.head_commit.timestamp }}
          **Check URL:** ${{ secrets.APP_URL || 'https://verber.sicole.com' }}
        color: 0xff0000